name: flutter_background_bar
description: flutter background + bar
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=2.19.6 <3.0.0'

dependencies:
  mpris:
    path: /mnt/general/repos/provokateurin/dart-mpris
  flutter:
    sdk: flutter
  flutter_hooks: ^0.18.6
  flutter_staggered_animations: ^1.1.1
  hooks_riverpod: ^2.3.6
  hyprland_ipc:
    git: 
      url: https://github.com/flafydev/hyprland_ipc.git

dev_dependencies:
  custom_lint: ^0.3.4
  riverpod_lint: ^1.3.1
  very_good_analysis: ^4.0.0+1

flutter:
  uses-material-design: true
  assets:
   - assets/
